##Adding version 2.0 for CIRCLE CI version Upgrade
version: 2
## Customize the test machine
jobs:
  build:
    machine: true
    environment:
      #Set the timezone
      TZ: "/usr/share/zoneinfo/America/New_York"
    python:
      version: 2.7.6
    ## Customize checkout
    steps:
      - checkout
      - run: git submodule sync
      - run: git submodule update --init
      - run: git submodule update --remote

      ## Customize dependencies
#      - run: "~/nvm/"
#      - run: "~/.npm/"
      - run: sudo pip install awscli

#- ./dev-ops/buildscripts/runTests.sh "https://web-dev.bridgestonehub.com/"

#          qa:
#            branch: qa
#           commands:
#              - run : echo deploying to us-east-1 && ./dev-ops/buildscripts/deploy.sh -a java -t quick -e qa -ci circle -r us-east-1
#             - run : echo deploying to ap-northeast-1 && ./dev-ops/buildscripts/deploy.sh -a java -t quick -e qa -ci circle -r ap-northeast-1
#- ./dev-ops/buildscripts/runTests.sh "https://web-qa.bridgestonehub.com/"

#          master:
#            branch: master
#            commands:
#              - run : echo deploying to us-east-1 && ./dev-ops/buildscripts/deploy.sh -a java -t full -e prd -ci circle -r us-east-1
#              - run : echo deploying to ap-northeast-1 && ./dev-ops/buildscripts/deploy.sh -a java -t full -e prd -ci circle -r ap-northeast-1
#- ./dev-ops/buildscripts/runTests.sh "https://www.bridgestonehub.com/"

## Custom notifications
