##Adding version 2.0 for CIRCLE CI version Upgrade
version: 2
## Customize the test machine
jobs:
  build:
    machine: true
    environment:
      #Set the timezone
      TZ: "/usr/share/zoneinfo/America/New_York"
    python:
      version: 3.6.8
    ## Customize checkout
    steps:
      - checkout
      - run: git submodule sync
      - run: git submodule update --init
      - run: git submodule update --remote

      ## Customize dependencies
      - run: aws --version
      - run: sudo dpkg -r awscli
      - run: cd /tmp 
      - run: sudo wget "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip"
      - run: sudo apt update 
      - run: sudo apt install -y unzip
      - run: sudo unzip awscli-exe-linux-x86_64.zip
      - run: sudo ./aws/install -i /usr/local/aws-cli -b /usr/local/bin
      - run: export PATH=$PATH:/usr/local/bin
      - run: aws configure list
      - run: aws --version
      - run: aws sts get-caller-identity


